# Artificial Neural Network

### Importing the libraries

In [66]:
import numpy as np
import pandas as pd
import tensorflow as ts

In [67]:
ts.__version__

'2.19.0'

## Part 1 - Data Preprocessing

In [68]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [69]:
print(X)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [70]:
print(y)

[1 0 1 ... 1 1 0]


### Importing the dataset

### Encoding categorical data

Label Encoding the "Gender" column

In [71]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [72]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [74]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [76]:
# important for deep learning
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [77]:
ann = ts.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [78]:
ann.add(ts.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [79]:
ann.add(ts.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [80]:
ann.add(ts.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [81]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy' , metrics= ['accuracy'])

### Training the ANN on the Training set

In [82]:
ann.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 525us/step - accuracy: 0.7819 - loss: 0.6190
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.8029 - loss: 0.4891
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.7954 - loss: 0.4588
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.8025 - loss: 0.4477
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.8065 - loss: 0.4351
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - accuracy: 0.8050 - loss: 0.4247
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.8172 - loss: 0.4070
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.8153 - loss: 0.4089
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.8075 - loss: 0.4177
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.8153 - loss: 0.4015
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.8117 - loss: 0.4203
Epoch 12/100
250/25

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [89]:
info = [[600, 'France', 1, 40, 3, 60000, 2, 1, 1, 50000]]
info = np.array(ct.transform(info))

print(info)

[[1.0 0.0 0.0 600 1 40 3 60000 2 1 1 50000]]


In [ ]:
info = sc.transform(info)


In [93]:
print(ann.predict(info) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[False]]


### Predicting the Test set results

In [95]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [97]:
from sklearn.metrics import confusion_matrix, accuracy_score
pm = confusion_matrix(y_test, y_pred)
print(pm)

asc = accuracy_score(y_test, y_pred)
print(asc)

[[1516   79]
 [ 195  210]]
0.863
